<a href="https://colab.research.google.com/github/GiulioG27/PyTorch-course/blob/main/00_pytorch_fundamentals_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## OO. PyTorch Fundamentals

Resource notebook:https://www.learnpytorch.io/



In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.1+cu124


In [4]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [5]:
#scalar

scalar=torch.tensor(7)
scalar




tensor(7)

In [6]:
scalar.ndim

0

In [7]:
#Get tensor back as PYthon int
scalar.item()


7

In [8]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim
#tip num of dims from the num of pair of square brackets

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
#MATRIX

MATRIX=torch.tensor([[7,8],[9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[1]

tensor([ 9, 10])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
#TENSOR
TENSOR= torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim


3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [19]:
TENSOR=torch.tensor([[[[1,2,3],[3,6,9],[2,4,5]]]])
TENSOR

tensor([[[[1, 2, 3],
          [3, 6, 9],
          [2, 4, 5]]]])

In [20]:
TENSOR.ndim

4

In [21]:
TENSOR.shape

torch.Size([1, 1, 3, 3])

### Random tensors

Why random tensors?

Random tensors are import because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random nubers ->look at data ->update random numbers-> look at data ->update random numbers`



In [22]:
#Create a random tensor of size (3,4)

random_tensor=torch.rand(3,4)
random_tensor


tensor([[0.3797, 0.5883, 0.7706, 0.1225],
        [0.9990, 0.0103, 0.7059, 0.5149],
        [0.8113, 0.6967, 0.0501, 0.5609]])

In [23]:
random_tensor.ndim


2

In [24]:
random_tensor=torch.rand(1,3,4)
random_tensor


tensor([[[0.5751, 0.9107, 0.0602, 0.7119],
         [0.4636, 0.4494, 0.0991, 0.7618],
         [0.0716, 0.1511, 0.9557, 0.2358]]])

In [25]:
random_tensor.ndim

3

In [26]:
#Create a random tensor with similar shape to an image tensor

random_image_size_tensor=torch.rand(size=(224,224,3)) #height,width,color channels(R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [27]:
random_tensor=torch.rand(3,4,5)
random_tensor

tensor([[[0.9771, 0.8495, 0.9435, 0.9959, 0.7420],
         [0.2508, 0.4123, 0.1201, 0.9681, 0.0722],
         [0.3794, 0.2587, 0.5805, 0.3501, 0.9680],
         [0.7324, 0.9704, 0.6552, 0.6124, 0.9744]],

        [[0.7625, 0.5026, 0.6516, 0.8074, 0.0187],
         [0.7078, 0.1034, 0.8738, 0.2972, 0.8238],
         [0.9852, 0.2371, 0.6712, 0.2985, 0.6051],
         [0.2029, 0.7522, 0.8454, 0.1591, 0.0074]],

        [[0.4378, 0.8902, 0.5829, 0.3773, 0.9142],
         [0.0930, 0.4799, 0.3869, 0.2450, 0.5754],
         [0.3150, 0.7131, 0.7324, 0.7806, 0.8709],
         [0.1467, 0.9054, 0.3193, 0.2751, 0.5276]]])

### Zeros and ones

In [28]:
# Create a tensor of all zeros
random_tensor=torch.zeros(size=(3,4))

zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
#Create a tensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [32]:
# Use torch.range()
torch.range(0,10)

<ipython-input-32-a70e3231c961>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [33]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
one_to_ten=torch.arange(start=1,end=11,step=1) #it finishes at end-1
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
# Creating tensors like
one_to_ten_like=torch.zeros_like(input=one_to_ten)
one_to_ten_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

# Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [36]:
#loat 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                              dtype=None,#what datatype is the tensor(e.g.float32 or float16)
                              device=None,#what device is ur tensor on #by the fault its "cpu", we can change with "cuda", if we try to do operations with tensors on different devices u gonna get an error
                              requires_grad=False) # if u want for PyTorch to track the gradient
float_32_tensor

tensor([3., 6., 9.])

In [37]:
float_32_tensor.dtype

torch.float32

In [38]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [39]:
float_16_tensor* float_32_tensor

tensor([ 9., 36., 81.])

In [46]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [47]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors
1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [49]:
# Create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.2779, 0.7285, 0.7760, 0.5398],
        [0.4935, 0.0695, 0.1393, 0.6262],
        [0.9552, 0.5265, 0.7701, 0.7695]])

In [51]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")
print(f"Tensor size: {some_tensor.size()}") #nb. size is not an attribute


tensor([[0.2779, 0.7285, 0.7760, 0.5398],
        [0.4935, 0.0695, 0.1393, 0.6262],
        [0.9552, 0.5265, 0.7701, 0.7695]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu
Tensor size: torch.Size([3, 4])


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [54]:
#Create a tensor and add 10 to it
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [55]:
#Multiply tensor by 10
tensor=tensor*10
tensor

tensor([10, 20, 30])

In [57]:
#Subtract 10
tensor-10

tensor([ 0, 10, 20])

In [58]:
#Try out PyTorch in-built functions
torch.mul(tensor,10)

tensor([100, 200, 300])

In [59]:
torch.add(tensor,10)

tensor([20, 30, 40])

 ### Matrix multiplication

 Two main ways of performing multiplication in neural networks and deep learning:

 1. Element-wise multiplication
 2. Matrix multiplication(dot product)

 There are two main rules that performing matrix multiplication needs to satisfy:
 1.The **inner dimensions** must match:
 * `(3,2) @ (3,2`) won't work
 * `(2,3) @ (3,2`) will work
 * `(3,2) @ (2,3`) will work                  
 2. The resulting matrix has the shape of the **outer dimensions** ...                             

In [62]:
#Element wise multiplication
tensor=torch.tensor([1,2,3])
print(tensor,"*",tensor)
print(f"Equals: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [63]:
#Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [64]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 1.98 ms, sys: 1.03 ms, total: 3 ms
Wall time: 2.7 ms


In [65]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 164 µs, sys: 0 ns, total: 164 µs
Wall time: 170 µs


tensor(14)

### One of the most common errors in deep learning:shape errors

In [67]:
# Shapes for matrix multiplication
tensor_A=torch.tensor([[1,2],[3,4],[5,6]])
tensor_B=torch.tensor([[7,10],[8,11],[9,12]])

#torch.mm(tensor_A,tensor_B) #torch.mm is the same as torch.matmul(it's an alias for torch.matmul)
#torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [68]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issures, we can manipulate the shape of one of our tensors using a **transpose**. A **transpose** switches the axes or dimensions of a given tensor


In [71]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [72]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [75]:
#The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


torch.Size([3, 3])

## Finding the min, max, sum,etc(tensor aggregation)

In [76]:
# Create a tensor
x=torch.arange(0,100,10)
x,x.dtype


(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [77]:
# Find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [78]:
#Find the max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [83]:
#Find the max - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [84]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

##Finding the positional min and max

In [87]:
#Find the posistion in tensor that has the minimum value with argmin()->returns index
torch.argmin(x),x.argmin()


(tensor(0), tensor(0))

In [88]:
torch.argmax(x),x.argmax()

(tensor(9), tensor(9))

## Reshaping, stacking, squeezinf and unsqueezing tensors

*Reshaping- reshapes an input tensor to a defined shape
*View- Return a view of an input tensor of certain shape but keep the same memory as the original tensor
*Stacking -combine multiple tensors on top of each other (vstack) or side by side (hstack)
*Squeeze - removes all `1` dimensions from a tensor
*Unsqueez -add a `1` dimension to a target tensor
*Permute- Return a view of the input with dimensions permuted (swapped) in a certain way


In [106]:
# Let's create a tensor
import torch
x= torch.arange(1.,10.)
x,x.shape


(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [117]:
#Add an extra dimension
x_reshaped=x.reshape(1,9) #the reshape has to be compatible with the original size
x_reshaped,x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [107]:
#Change the view
z=x.view(1,9) #a view shares the memory with the original tensor
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [108]:
#Changing z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [112]:
#Stack tensors on top of each other
x_stacked=torch.stack([x,x,x,x],dim=0                               )
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [125]:
#torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")


x_reshaped


Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [128]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim

print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape: torch.Size([9, 1])


In [130]:
#torch.permute - returns a view of the original tensor with dimensions permuted(rearranged)
x_original=torch.rand(size=(224,224,3)) #[height,width,colour_channels]

#Permute the orginal tensor to rearrange the axis (or dim)
x_permuted=x_original.permute(2,0,1) #shifts axis 0->1,1->2,2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[colour_channels,height,width]
#Watch out they still share the same memory



Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [133]:
x_original[0,0,0]=728218
x_original[0,0,0],x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

## Indexing(selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [134]:
#Create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [135]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [137]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [138]:
#Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [139]:
# You can also use ":" to select "all" of a target dim
x[:,0]

tensor([[1, 2, 3]])

In [140]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [141]:
#Get all values of the 0 dimension  but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [143]:
x[0,1,1] #notice no square brackets in the result

tensor(5)

In [145]:
#Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [150]:
# Index on x to return 9
print(x[0,2,2])

#Index on x to return 3,6,9
print(x[0,:,2])


tensor(9)
tensor([3, 6, 9])


## PyTorch tensors and NumPy

NumPy is a popular scientific Python numerical computing library, and because of this, PyTorch has functionality to interact with it

*Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`

*PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`


In [155]:
#NumPy array to tensor

import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array) #warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [152]:
array.dtype

dtype('float64')

In [153]:
torch.arange(1.0,8.0).dtype

torch.float32

In [156]:
# Change value of array, what will this do to "tensor"?

array= array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [157]:
#Tensor to NumPy array
tensor=torch.ones(7)
numpy_tensor=tensor.numpy() #it reflects the original type of the tensor
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [158]:
# Change the tensor, what happens to numpy tensor?

tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In short how a neural networ learns:

`start with random numbers->tensors operations->update random numbers to try and make them better representations of the data->again->again->again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.



In [160]:
import torch

#Create two random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.0974, 0.6873, 0.7839, 0.9966],
        [0.5550, 0.0092, 0.9345, 0.7765],
        [0.6902, 0.9473, 0.4187, 0.8272]])
tensor([[0.6688, 0.3248, 0.9352, 0.7706],
        [0.1863, 0.3843, 0.6740, 0.9664],
        [0.0613, 0.1213, 0.5825, 0.0371]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [162]:
# Let's make some random but reproducable tensors
import torch

# Set the random seed
RANDOM_SEED= 42 #up to u but commonly 42

torch.manual_seed(RANDOM_SEED) #setting the manual seed everytime u call randpytor
random_tensor_C=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs=faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch woring behind the scenes to make everything hunky dory(good)


### 1. Getting a GPU

1. Easies - Use Google Colab for a free GPU (options to upgrade as well)
2. Use ur own GPU - takes a ittle bit of setup and requires the investment of purchasing a GPU
3. Use cloud computing - GCP. AWS, Azure, these services allow you to rent computers on the cloud and access them



In [1]:
!nvidia-smi

Wed Feb  5 18:58:33 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   38C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

### 2. Check for GPU access with PyTorch



In [2]:
# Check for GPU access with PyTorch

import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html#best-practices
E.g. run on GPU if available, else default to CPU

In [3]:
# Setup device agnostic code
device= "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want out tensors/models on the GPU is because using a GPU results in faster computations


In [6]:
# Create a tensor (default on the CPU)

tensor=torch.tensor([1,2,3])

#Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
#Move tensor to GPU (if available)

tensor_on_gpu= tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the cPU (fro eg to use Numpy that works only on cpu)


In [8]:
# If tensor is on GPU, can't transform it to NumPy
#tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [9]:
#To fix the GPU tensor with NumPy issue, we can first set it to the CPU

tensor_back_on_cpu= tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercises & extra-curriculum